#docker-compose file
version: '3'

services:
  nestapp:
    container_name: your_app
    image: your_app:1.0.0
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    env_file:
      - .env
